version: '3.8'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    # Using the lightest distribution with alpine.
    image: 'rabbitmq:3.8-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # For the actual instance of RabbitMQ.
      - '5672:5672'
      # For the web interface.
      - '15672:15672'